version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 224935473367.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ratepay .
      - docker tag ratepay:latest 224935473367.dkr.ecr.eu-central-1.amazonaws.com/ratepay:latest
      - docker push 224935473367.dkr.ecr.eu-central-1.amazonaws.com/ratepay:latest
